name: Run Test

on:
  pull_request:
    branches: [main]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      # - name: Flutter Pub Get
      #   run: flutter pub get
      # - name: Flutter Test
      #   run: flutter test --coverage
  coverage_report:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - run: which lcov
      - run: which genhtml
